### ISSUE TITLE
feat: 기존 gsheet의 누적개근횟수를 반영하는 DB 세팅을 위한 API 작성

### ISSUE THREAD

**Issue by refigo** [42Mogle/42-mogle-backend#111]
## Think
[Date: 2023-01-30]
기존에 사용하던 google spread sheet에는 과거의 누적개근 횟수가 기록되어 있다.
42mogle 웹서비스는 중간에 만들어졌기 때문에 과거의 누적개근횟수가 업데이트 되어 있지 않다.
과거에 기록되어 있던 누적개근횟수를 DB에 어떻게 등록시킬지 고민이 되었다. 생각한 방안은 3가지 정도 나왔다.
1. 과거 출석 기록들을 모두 등록한다.
2. 과거에 특정달마다 개근한 사람들만 누적개근횟수와 함께 등록한다.
3. 기존 데이터가 없던 달 중에 최신인 2022년 11월의 MonthlyUsers에 모든 유저들을 등록시키고 11월 까지의 누적개근횟수를 그 DB에다가 넣는다.

모닝글로리 특성상 과거 출석데이터를 참조할 일은 거의 없을 것 같다. 그러므로 방안1은 제외한다.
누적개근횟수도 과거의 특정월 정보를 참조할 일은 거의 없을 것 같다. 방안2 또한 제외한다.
방안3은 42mogle 개발을 시작한 11월 데이터에 이전 누적개근횟수들을 모두 추가하는 방법이다. 이 방법을 사용하면 현재 월의 누적개근횟수를 업데이트할 때 사용하는 베이스가 될 것 이다. 2022년 12월 이전의 정확한 월 데이터를 참조할 수는 없지만 그럴리는 잘 없고 현재와 같은 상황에서 빠르게 로직을 업데이트할 수 있는 방법이다.
그러므로 일단 방안3으로 진행하자.

## todos
- [x] 2022년 11월 month_info 세팅
- [x] 기존 gsheet의 누적개근횟수 등록을 위한 API 구현
- [x] gsheet의 개근자 목록과 누적개근횟수 데이터 정제 (csv 형식으로)
- [x] 정제된 데이터를 가진 csv를 바탕으로 구현한 API를 호출하는 python script 작성
- [x] 누적개근횟수 등록 실행 및 확인
