### ISSUE TITLE
[BE] 백엔드 컨테이너화

### ISSUE THREAD

**Issue by Han-Joon-Hyeok** [42Mogle/42-mogle-backend#137]
# 개요

- AWS EC2에서 로컬로 실행하던 서비스를 컨테이너화 하여 AWS ECS에서 운영하고자 합니다.

# Todo

- [x] Dockerfile 생성
- [x] docker-compose.yml 파일 생성
- [ ] pm2 로 서비스 실행
- [ ] 42 api renewal cron 설정
