### ISSUE TITLE
보충 출석 로직 변경 (주말 및 공휴일 모든 보충출석 1회 -> 정규 출석 1회로 인정)

### ISSUE THREAD

**Issue by refigo** [42Mogle/42-mogle-backend#147]
## 변경된 사항
- 주말 보충 출석 2회를 정규 출석 1회 인정에서 => **주말 및 공휴일 모든 보충출석 1회를 정규 출석 1회로 인정**

## TODO
- [x] 현시점 DB 백업
- [x] 보충 출석 로직 코드 변경 in StatisticService
- [x] 현재 운영 중인 서비스 DB에 해당 변경 사항 반영
