### ISSUE TITLE
feat: setting Swagger

### ISSUE THREAD

**Issue by refigo** [42Mogle/42-mogle-backend#4]
**Todos**
- [x]  swagger in nestJS
    - [x]  read: ****[Nest.js] swagger 적용하기****
        
        [[https://velog.io/@___pepper/Nest.js-swagger-적용하기](https://velog.io/@___pepper/Nest.js-swagger-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)](https://velog.io/@___pepper/Nest.js-swagger-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)
        
    - [x]  set: swagger in the project

- Related branch
    https://github.com/42Mogle/42-mogle-backend/issues/4
